[package]
name = "patronus"
version = "0.24.0"
edition = "2021"
authors = ["Kevin Laeufer <laeufer@berkeley.edu>"]
description = "Hardware bug-finding toolkit."
readme = "Readme.md"
repository = "https://github.com/ekiwi/patron"
homepage = "https://kevinlaeufer.com"
license = "BSD-3-Clause"
keywords = ["RTL", "btor", "model-checking", "SMT", "bit-vector"]
exclude = [".github/", ".gitignore"]

[dependencies]
indexmap = "2.0.0"
codespan-reporting = "0.11.1"
fuzzy-matcher = "0.3.7"
lazy_static = "1.4.0"
easy-smt = "0.2.1"
# used for simulator initialization
rand = { version = "0.8.5", default-features = false }
rand_xoshiro = "0.6.0"
smallvec = { version = "1.x", features = ["union"] }
baa = "0.14.5"
boolean_expression = "0.4.4"
egg = "0.9.5"
rustc-hash = "2.0.0"
regex = "1.11.1"
ndarray = "0.15"
linfa = "0.7.0"
linfa-trees = "0.7.0"
csv = "1.1"
rustlearn = "0.5.0"
rustrees = "0.2.4"
rayon = "1.7.0"
pyo3-ffi = "0.18.1"
pyo3 = "0.18.1"
arrow = "37.0.0"
permutation = "0.4.1"

[dev-dependencies]
clap =  { version = "4.4.8", features = ["derive"] }
insta = { version = "1.34.0", features = ["yaml"] }

[profile.dev.package]
insta.opt-level = 3

[profile.release]
debug = true
